{% set name = "gds-swig" %}
{% set version = "3.0.0" %}

# dependencies
{% set gds_base_version = "3.0.0" %}
{% set gds_frameio_version = "3.0.0" %}
{% set gds_lsmp_version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://software.igwn.org/sources/source/{{ name }}-{{ version }}.tar.gz
  sha256: 649cbbd4320ac58d8ccba903b8ff01f7ed5b01cf075d9acabc4ab27528ba2473
  patches:
    # backport 96c2a6050f1eec31b6d4c7cb55c4d717abc22c9b
    - 0001-Replaced-AC_PYTHON_DEVEL-with-AX_PYTHON_DEVEL-to-avo.patch

build:
  number: 1
  skip: true  # [win]

outputs:
  - name: python-gds
    script: build-pygds.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
        - make
        - pkg-config
        - swig >=2.0.11
        # to support autoreconf with patches
        - autoconf
        - automake
      host:
        - gds-base >={{ gds_base_version }}
        - gds-frameio-base >={{ gds_frameio_version }}
        - gds-lsmp >={{ gds_lsmp_version }}
        - libboost-headers
        - numpy
        - python
      run:
        - gds-base >={{ gds_base_version }}
        - gds-frameio-base >={{ gds_frameio_version }}
        - gds-lsmp >={{ gds_lsmp_version }}
        - {{ pin_compatible('numpy') }}
        - python
    test:
      imports:
        - gds.pygdsdata
        - gds.pygdsio
        - gds.pygdssigp
    about:
      home: http://www.lsc-group.phys.uwm.edu/daswg/projects/dmt.html
      dev_url: https://git.ligo.org/gds/gds.git
      license: GPL-2.0-or-later
      license_file: COPYING
      summary: Python wrappers for GDS classes
      description: |
        Python wrappers of some of the most useful GDS classes

about:
  home: http://www.lsc-group.phys.uwm.edu/daswg/projects/dmt.html
  dev_url: https://git.ligo.org/gds/gds.git
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: SWIG bindings for GDS
  description: Global diagnostics software SWIG bindings

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
