{% set name = "gds-swig" %}
{% set version = "3.0.0" %}

# dependencies
{% set gds_base_version = "3.0.0" %}
{% set gds_frameio_version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://software.igwn.org/sources/source/{{ name }}-{{ version }}.tar.gz
  sha256: 649cbbd4320ac58d8ccba903b8ff01f7ed5b01cf075d9acabc4ab27528ba2473
  patches:
    # to update the patches for a new release:
    #
    #     # -- checkout the new source release tag
    #     cd /path/to/git/gds
    #     git fetch
    #     git checkout <release-tag>
    #     # -- apply the patches on top of the release tag
    #     git am --3way /path/to/git/gds-swig-feedstock/recipe/patches/*.patch
    #     <resolve-any-conflicts>
    #     # -- render new patch files
    #     rm -rf swig-patches/*.patch
    #     git format-patch <release-tag> wrappers/swig/ -o swig-patches
    #     # -- copy them back to the feedstock
    #     cd /path/to/git/gds-swig-feedstock
    #     git rm recipe/patches/*.patch
    #     cp /path/to/git/gds/swig-patches/*.patch recipe/patches/
    #     git add recipe/patches/*.patch
    #     <update-this-file-as-required>

    # backport 96c2a6050f1eec31b6d4c7cb55c4d717abc22c9b
    - patches/0001-Replaced-AC_PYTHON_DEVEL-with-AX_PYTHON_DEVEL-to-avo.patch
    # hack fix for https://git.ligo.org/gds/gds/-/issues/185
    - patches/0002-swig-disable-multi-module-support.patch
    # backport https://git.ligo.org/gds/gds/-/merge_requests/298
    - patches/0003-swig-update-numpy.i.patch

build:
  number: 4
  skip: true  # [win]

outputs:
  - name: python-gds
    script: build-pygds.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - make
        - pkg-config
        - swig >=2.0.11
        # to support autoreconf with patches
        - autoconf
        - automake
      host:
        - gds-base >={{ gds_base_version }}
        - gds-frameio-base >={{ gds_frameio_version }}
        - libboost-headers
        - numpy
        - python
      run:
        - gds-base >={{ gds_base_version }}
        - gds-frameio-base >={{ gds_frameio_version }}
        - numpy
        - python
    test:
      imports:
        - numpy
        - gds.pygdsdata
        - gds.pygdsio
        - gds.pygdssigp
    about:
      home: http://www.lsc-group.phys.uwm.edu/daswg/projects/dmt.html
      dev_url: https://git.ligo.org/gds/gds.git
      license: GPL-2.0-or-later
      license_file: COPYING
      summary: Python wrappers for GDS classes
      description: |
        Python wrappers of some of the most useful GDS classes

about:
  home: http://www.lsc-group.phys.uwm.edu/daswg/projects/dmt.html
  dev_url: https://git.ligo.org/gds/gds.git
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: SWIG bindings for GDS
  description: Global diagnostics software SWIG bindings

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
